apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::369681777804:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-89TW3FM02SN4
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-15T10:41:55Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1533"
  uid: 7cf524d6-6e78-42ff-be49-b480254e6fa9
