apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::671266162866:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1RP5O84A3TDWE
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::671266162866:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-11T12:59:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "4179"
  uid: 6d1335b9-84b6-4272-b27c-7eb2aa6f452c
